name: inception



services:
  mariadb:
    container_name: mariadb
    env_file: .env

    build: requirements/mariadb
    restart: always
    networks:
      - default
    volumes:
      - database:/var/lib/mysql

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env

    build: requirements/wordpress
    restart: always
    networks:
      - default
    volumes:
      - html:/var/www/html


  nginx:
    container_name: nginx
    depends_on:
      - wordpress

    build: requirements/nginx
    restart: always
    networks:
      - default
    ports:
      - "8443:443"
    volumes:
      - html:/var/www/html



networks:
  default:



volumes:
  database:
    driver_opts:
      type: none
      o: bind
      device: /home/opelser/Desktop/inception/database


  html:
    driver_opts:
      type: none
      o: bind
      device: /home/opelser/Desktop/inception/html