name: inception

services:
  mariadb:
    container_name: mariadb

    env_file: .env
    restart: always
    networks:
      - default

    image: mariadb
    # build: requirements/mariadb
    ports:
      - "3306:3306"
    # volumes:
    #   - database:


  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb

    restart: always
    networks:
      - default

    image: wordpress
    # build: requirements/wordpress
    ports:
      - "9000:9000"
    volumes:
      - html:/var/www/html/


  nginx:
    container_name: nginx
    depends_on:
      - wordpress

    restart: always
    networks:
      - default

    image: nginx
    # build: requirements/nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - html:/usr/share/nginx/html



networks:
  default:
    name: inception-network



volumes:
  database:
  html: