name: inception



services:
  mariadb:
    container_name: mariadb
    env_file: .env

    build: requirements/mariadb
    restart: always
    networks:
      - default


  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb

    build: requirements/wordpress
    restart: always
    networks:
      - default


  nginx:
    container_name: nginx
    depends_on:
      - wordpress

    build: requirements/nginx
    restart: always
    networks:
      - default
    ports:
      - "8443:443"



networks:
  default:
    name: inception-network