name: inception


services:
  mariadb:
    container_name: mariadb
    env_file: .env
    restart: always
    networks:
      - default
    build: requirements/mariadb

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - default
    build: requirements/wordpress

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    networks:
      - default
    build: requirements/nginx
    ports:
      - "8443:443"
      - "8080:80"


networks:
  default:
    name: inception-network